### ISSUE TITLE
update data-raw/mood_dem.csv

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_dem_mood#1]
This file needs committed to the repo (and finished up with the evs data).

**Comment by casstai** [comment]
@fsolt The mood_dem is updated based on Claassen's ajps 2019 piece.  
Three notes: 1. Claassen's data doesn't include eurob2936 data which is in our data. 
2. amb_combo_2004 means the data in the year 2004 in amb_combo.
3. Add strong leader item for pew 2017.

**Comment by casstai** [comment]
add wvs7 demsupport-related questions in mood_dem.csv. Only 4 questions, strong leader, arm rule, the importance of dem, and evaluation.    Aha,  now I think I get the general idea what @fsolt did on the column of item_con.

**Comment by Tyhcass** [comment]
> add wvs7 demsupport-related questions to mood_dem.csv. Only 4 questions, strong leader, arm rule, the importance of dem, and evaluation. Aha, now I think I get the general idea what @fsolt did on the column of item_con.
