### ISSUE TITLE
paper: title

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_dem_mood#11]
We need a title.  I propose "Public Support for Democracy and Regime Survival" because:

1. My lame formula for titles is always "IV and DV."  It gets the job done.
2. This one hits key words from the title of Claassen (2020 so will hopefully help it pop up in Google searches for that article while
3. also sounding distinctly different from the title of Claassen (2020)

We _could_ add "Revisiting . . . " or " . . . Revisted" if we wanted to highlight that we were replicating, but that isn't the framing we're going for.  If we come up with a clever title, we could have a colon before or after and then have our clever title.

**Comment by fsolt** [comment]
If we _really_ wanted to market DCPO, we could add ": An Analysis of Dynamic Comparative Public Opinion" but honestly that strikes me as overkill.

**Comment by fsolt** [comment]
I still think "Public Support for Democracy and Regime Survival" isn't bad.  Hmm.  "Public Support for Democracy, Regime Change, and the Importance of Incorporating Measurement Uncertainty" sounds like (a) we're making a methods contribution [we do!], (b) keeps both directions of the relationship open [we look at both!], and (c) also somehow a bit of a mystery novel [intriguing?!? idk].  Thoughts?  Alternatives?  

Also tagging @lallemang and @byngdeuk to get thoughts and ideas from the rest of the lab.

**Comment by sammo3182** [comment]
Given we are focusing on uncertainty, should we highlight it in the title? Maybe: "Uncertainty Matters: An Alternative Story of Public Support and the Survival of Democracy" or "Public Support Helps Democracy Survive? When Estimated Uncertainty Is Taken into Account"

**Comment by fsolt** [comment]
Agreed: "Uncertainty" should be in there somewhere.  I'm not sure "Survival" is not as desirable, though, because it puts the focus more on the AJPS replication--the thermostatic relationship goes both ways, up and down, after all--when I think we could balance the treatment of the two pieces.

**Comment by fsolt** [comment]
Promising starts, though.  Thanks, Hu!  More ideas?  Building on these, or others?

**Comment by casstai** [comment]
Play with puns? Like, Public Support for Democracy versus Regime Change？Uncertainty.

**Comment by sammo3182** [comment]
I'm a little hesitant about the "Regime Change" part, a lower democratic score does not imply a regime change, right? On the other hand, enlightened by Cassandra's line:

1.  Certain Uncertainty: Public Support for Democracy Based on a Global Examination
1. Only the Uncertainty Is Certain: A Cross-National Time-Series Examination of Public Support for Democracy

**Comment by fsolt** [comment]
These last few strike me as forced, tbh—I don't think it is _certain_ that we would have uncertainty in our conclusion, it's just that we do in this case (because we don't have enough data or the [source measures lacks validity](https://github.com/fsolt/dcpo_dem_mood/issues/10#issuecomment-669176256) or the theory truly isn't good, etc., etc.).

And imo the issue with [these earlier ideas](https://github.com/fsolt/dcpo_dem_mood/issues/11#issuecomment-717661035) is that they lean hard on the opinion -> democracy link, when I think ideally we'd maintain balance between the two research questions.

Subbing "Democratic Change" for "Regime Change" in the title on there now addresses [Hu's point](https://github.com/fsolt/dcpo_dem_mood/issues/11#issuecomment-719109275), I think, giving:
"Public Support for Democracy, Democratic Change, and the Importance of Incorporating Measurement Uncertainty."

We could go shorter, too: "Democracy, Public Support, and the Importance of Measurement Uncertainty"

Or at the extreme, just: "Democracy, Public Support, and Measurement Uncertainty"

**Comment by sammo3182** [comment]
Aye for  "Democracy, Public Support, and Measurement Uncertainty"

Or "How Does Democracy Relate to Public Support? Stories Changes When Measurement Uncertainty Is Accounted"

**Comment by sammo3182** [comment]
No problem of the title from the R&R
