### ISSUE TITLE
analysis: apsr replication 

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_dem_mood#13]
theta as DV

- [x] Replication

- [x] All data, DCPO point estimates

- [x] All data, DCPO with uncertainty

**Comment by sammo3182** [comment]
Ok, something...I'm not sure if I got correctly. I replicate the APSR. The point estimator looks fine: again DCPO produces null results for a key variable:

![image](https://user-images.githubusercontent.com/6463211/91524999-1dc0cd00-e933-11ea-9082-e5eb4359699f.png)

The more impressive part comes from the uncertainty. Remember we very the DV (and IV---the lags--- actually) now, and it dramatically changes the results. It's already not "sig to null" but also changing the directions:

![image](https://user-images.githubusercontent.com/6463211/91525137-66788600-e933-11ea-8733-67cefdb39198.png)

I didn't find any suspicion of incorrect coding, but I still can't believe the variance of DV can make such a big difference. I need a second pair of eyes to double-check for me, guys. When you have a moment, could you please have a look at the following lines? https://github.com/fsolt/dcpo_dem_mood/blob/6c73870d3358da6efc912f059fd67aa3c9bd2247/paper/dcpo_demsupport.Rmd#L649-L693 Thanks a lot! @fsolt @Tyhcass

**Comment by casstai** [comment]
My understanding is if it is null，the direction doesn't matter. I will check the codes But I don't think your codes are wrong..
