### ISSUE TITLE
Uncertainty Affects Point Estimates

### ISSUE THREAD

**Issue by sammo3182** [fsolt/dcpo_dem_mood#15]
E: Reviewers 1, 2, and 4 all ask why the results for Claassen's model but accounting for measurement error (second set of results) also **yield different point estimates**. The revised version should address this directly, including by better explaining the method(s) used. If the difference in point estimates is due to multiple deviations from Claassen's approach (e.g., in both the smoothing _and_ the use of the errors), I would suggest introducing and presenting each intermediate modification of the research design incrementally to avoid confusion and help readers assess how much of the change in results is due to the incorporation of measurement error vs. other modeling or measurement decisions. Analytical transparency is key.     

R1: They appear to show that democratic support is entirely disconnected from such prominent features of the political environment as the level of democracy and economic development. Not only are these effects insignificant, but **their point estimates are almost exactly zero in magnitude**. The effects of **lagged democratic support are also zero**, which is even more implausible because it suggests that democratic support in one year is entirely disconnected from its levels in previous years. In other words, Denmark is as likely to have a low-value next year as China is likely to have a high value. This stands in contrast with much of existing research on democratic support and political culture...The authors might use a different method for factoring in the error due to measurement: **structural equation models, which, in essence, combine a measurement model and the subsequent regression model in one step.** In contrast to the method proposed in the present paper, SEMs benefit from substantial methodological literature (e.g., Bollen & Noble 2011; Skrondal & Rabe-Hesketh 2004). Indeed, one of the articles cited by the current paper (Juhl 2019) adopts exactly this approach. 

R2: Also, I could not help but be struck by the extreme attenuation of the coefficient estimates in Figure 2, which almost suggest that the variables were generated from independent distributions. In particular, can it really be the case that **lagged support has no conditional association with current support**? If so, then I think some explanation is required, or else readers will think that some mistake has been made.

R4:  I was a bit confused by Figures 1 and 2. My understanding is that accounting for uncertainty should only affect the standard errors, but in the figures it also affects the point estimates. This is the case even in the models 'Claassen W/Uncertainty.'

**Comment by fsolt** [comment]
Part of this, on null results for lagged DV in Fig 2, goes to #24

**Comment by fsolt** [comment]
The idea that uncertainty only affects standard errors---and not the point estimates---is a common misconception (obviously very common).  I've been working with data with uncertainty for like a decade now with the SWIID, so I sometimes forget that people don't know this (although people working with the SWIID bring it up with me from time to time---I should know that people don't know).  It'll be a helpful point for us to demonstrate.
