### ISSUE TITLE
Incorporating Error by Multiple Overimputation (Methodological Citations Needed)

### ISSUE THREAD

**Issue by sammo3182** [fsolt/dcpo_dem_mood#17]
R1: My primary concern is that the method by which measurement error is included / added is not sufficiently explicated and demonstrated to be valid (e.g., using Monte Carlo experiments), especially in the time-series, cross-sectional context which is of interest. The authors **cite several applied articles - none of which appears to be methodological in nature** .

R2: The MS deals with measurement error by treating mismeasured variables as if they were fully imputed, and following Rubin's standard multiple imputation rules. If I understand correctly, this is what **Blackwell, Honaker, and King (2017) call "multiple overimputation" (MO)—a fact that should probably be noted in the MS**, given that Blackwell et al. provide the most comprehensive exposition of this method that I am aware of. Taking an MO approach has dramatic effects on Claassen's results. For models with democracy as the DV (Figure 1), it hugely increases the estimated uncertainty of all the coefficient estimates. For the "thermostatic" model with public support as the DV (Figure 2), it massively attenuates the point estimates as well. Using the MS's own DCPO measurement model instead of Claassen's mitigates some of this added uncertainty but does not qualitatively affect the conclusion that Claassen's conclusions are not robust. If true, this conclusion is quite substantively important...First, the MS should provide more detail on the theoretical justification for MO and the conditions under which it performs well. How does it perform when measurement error is strongly correlated across variables, as is likely to be the case in the models with lagged DVs?

**Comment by fsolt** [comment]
E: Both Reviewers 1 and 2 want more evidence, explanation, and/or justification of the alternative method used to incorporate measurement error. Reviewer 1 seems to specifically suggest a simulation study. If such a study already addresses the performance of the method (either analytically or with simulations) in a context with temporally and serially correlated errors, it would make sense to reference that work in the main text.

R4: We need more information on (1) how uncertainty is integrated into the models of Claassen, and (2) the DCPO models.

**Comment by fsolt** [comment]
Blackwell, Honaker, and King (2017, 333) specifically note the approach works for TSCS data
