### ISSUE TITLE
Include Claassen's Alternate Specifications in Appendix

### ISSUE THREAD

**Issue by sammo3182** [fsolt/dcpo_dem_mood#22]
E:  I could imagine some readers benefitting from having the estimating equations included in the Supplemental Information in order to appreciate how measurement error is incorporated into the estimates as well as more information about the levels of measurement used (mentioned as an important difference by Reviewer 3). **While Reviewer 1 asks for all results from the original two studies be replicated as well, these additional replications need only be included in the paper or SI to the extent that they are relevant to the relationship between support and democracy at the core of this Letter's focus. **

R1: Claassen 2020a argues that within-country analyses are desirable and uses generalized method of moments (GMM) estimators to obtain these. Claassen (2020b) uses first difference models; he also focuses on the separate effects of the electoral and liberal components of democracy. I suggest that the authors replicate all the main results from Claassen (2020a; 2020b), rather than an ad hoc subset of these. 

- [x] GMM of Claassen 2020a
- [x] FD of Claassen 2020b
- [x] Separated model of electoral and libera components of democracy of Claassen 2020b
- [ ] Equations of measurement errors in the SI
- [ ] Elaborating the level of measurement according to R3.

**Comment by fsolt** [comment]
Hey Hu, it looks like you brought a lot of this into the text, rather than just the appendix.  Do you think that they are an important addition?

**Comment by sammo3182** [comment]
Fred, right. In the current version, I put the alternative models besides the major ones. It was just because I was checking whether they produce the substantively identical results as the main model after dealing with the uncertainty, and it is easy to do the check within one plot. As we planned yesterday, I'll move all of them to the appendix later in this week 😁
