### ISSUE TITLE
Explain Null Results for Lagged DV in Fig 2

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_dem_mood#24]
R1: Second, the results in Figure 2, based on models using democratic support as a dependent variable, are puzzling. They appear to show that democratic support is entirely disconnected from such prominent features of the political environment as the level of democracy and economic development. Not only are these effects insignificant, but their point estimates are almost exactly zero in magnitude. The effects of lagged democratic support are also zero, which is even more implausible because it suggests that democratic support in one year is entirely disconnected from its levels in previous years. In other words, Denmark is as likely to have a low value next year as China is likely to have a high value. This stands in contrast with much of existing research on democratic support and political culture. 

R2: Also, I could not help but be struck by the extreme attenuation of the coefficient estimates in Figure 2, which almost suggest that the variables were generated from independent distributions. In particular, can it really be the case that lagged support has no conditional association with current support? If so, then I think some explanation is required, or else readers will think that some mistake has been made.

**Comment by fsolt** [comment]
- [x] Confirm there's no bug here
- [x] If not, discuss

**Comment by casstai** [comment]
added discussion on [1556296](https://github.com/fsolt/dcpo_dem_mood/commit/15562968e7920c64cf5d9bfeeccee56a9f417ed8)
