### ISSUE TITLE
Consider Including 2020 Data?

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_dem_mood#25]
No one:
Literally nobody: 
Me: V-Dem now has 2020 data, so we could expand the "more data" analyses.  V-Dem was the holdup, right?  We probably have more public opinion data, now, too

**Comment by fsolt** [comment]
Thoughts,  @sammo3182 and @Tyhcass?

**Comment by sammo3182** [comment]
No reviewers comment on the data issue. This may not be a primary task to do? Nor do I think one more year's data would improve the result in some way...

**Comment by fsolt** [comment]
Yeah, agreed.  What was a priority was the "consider" part—and if it were going to be done, it should be done first thing.  Okay, it's been considered.  (Don't make us change our mind, @Tyhcass!  I shouldn't have brought it up in the first place.)
