### ISSUE TITLE
Incorporate the SI to the main rmd file

### ISSUE THREAD

**Issue by sammo3182** [fsolt/dcpo_dem_mood#26]
We separate them now, and I saw many scholars did the same. But I sort of lose the point of doing so. Adding the appendix into the main rmd will prevent extra data loading and easy for us to cite the SI sections. Fred and Cassandra, should we have a try at it? Or is there any specific concern of doing so?

**Comment by fsolt** [comment]
I can think of two: 1. I _think_ Editorial Manager requires them as two separate PDFs when submitting, and 2. they'll definitely want them separate at the publication stage.  Granted, we can always split them ourselves manually when we get to that point.  Any other reasons you can think of, @Tyhcass ?

**Comment by casstai** [comment]
We can have a try, but I think finally they will require us to separate the main section and SI.

**Comment by sammo3182** [comment]
Done with the commit eeea4386873134255517d6e105c992ddcb1faea1
