### ISSUE TITLE
Data stats updated in the content

### ISSUE THREAD

**Issue by sammo3182** [fsolt/dcpo_dem_mood#28]
Update the expanded data statistics on line 318 https://github.com/fsolt/dcpo_dem_mood/blob/eca30a0153d51ca7cb9ea8c733c04c0164bde82f/paper/dcpo_demsupport.Rmd#L318

The current version was based on the old dcpo data.

**Comment by casstai** [comment]
Done. I have updated the comparison using exp_claassen_input.rda
