### ISSUE TITLE
TSCS context

### ISSUE THREAD

**Issue by sammo3182** [fsolt/dcpo_dem_mood#30]
_APSR RR2_

## Editor

> I would encourage you to acknowledge or engage the points - not with additional analyses necessarily - but a brief acknowledgment or discussion of why these three points are or are not relevant as other readers may have similar questions, particularly about the appropriateness of this approach for TSCS data as well as how this approach compares (analytically) to structural equation models, which as you are likely aware have a long history in the study of democracy (and development, specifically).

## R1

> These points have unfortunately not been addressed by the authors in their revision and memo. They have, however, been addressed in another analysis of this research question by Claassen (2021). Claassen (2021) shows that when combining measurement models and subsequent regression models in one step, results are quite different from those presented in the paper under consideration (and substantively similar to those originally presented by Claassen 2020a,b). Indeed, Claassen (2021) shows that when it comes to the link between support and democratic change, the "method of composition" (which is used in the current paper) is the only method of including measurement uncertainty which leads to null results.

**Comment by fsolt** [comment]
Closed by 037a0c668cb55f1d1a9fc0f23dd5390b7332f572, which highlights that MOC requires no change to model specification
