### ISSUE TITLE
Covariates yield estimates near zero 

### ISSUE THREAD

**Issue by sammo3182** [fsolt/dcpo_dem_mood#32]
_APSR RR2_

## Editor

> I would encourage you to acknowledge or engage the points - not with additional analyses necessarily - but a brief acknowledgment or discussion of why these three points are or are not relevant as other readers may have similar questions, particularly about the appropriateness of this approach for TSCS data as well as how this approach compares (analytically)

## R1

> I also note with concern, once again, how many of the estimated parameters are centered exactly at zero. According to Figure 2, zero effects can be observed for many of the covariates: change in GDP, change in corruption, change in democracy, etc. While I am willing to believe a model that produces generally insignificant effects, I find it implausible when so many covariates have effects of exactly zero. This strikes me as a canary in a coalmine. The authors' dismissal of this concern as due to the use of an ECM does not address the zero effects seen for covariates: these parameters do not differ across the ECM and ADL specifications. In addition, when using the same method of composition and virtually the same data, Claassen (2021) finds very different results for covariates such as change in log GDP per capita.

**Comment by fsolt** [comment]
> The authors' dismissal of this concern as due to the use of an ECM does not address the zero effects seen for covariates

Um, yes it does 
![image](https://user-images.githubusercontent.com/6536645/147357670-73393d25-4f70-4255-b144-47401aa8319f.png)

> In addition, when using the *same method of composition* and virtually the same data, Claassen (2021) finds very different results for covariates such as change in log GDP per capita.

This is untrue: Claassen (2021) uses the MOC *with a SEM* (i.e., he changes the model specification)

**Comment by fsolt** [comment]
closed by 2e3a496e95fa239448e3986b76519802624981fb
