### ISSUE TITLE
Contribution reframing

### ISSUE THREAD

**Issue by sammo3182** [fsolt/dcpo_dem_mood#33]
_APSR RR2_

> In addition, in your memo, you frame your contribution as two-fold: a substantive point about democracy and a methodological one about measurement error. However, the abstract, framing, and discussions/conclusions tend to emphasize the former more than the latter. I would encourage you to **revise some of the text to draw out the methodological insights further**, such that researchers who might not be interested in this specific substantive debate but who use similar aggregate public opinion measures in cross-national analyses are able to connect your approach to their substantive areas of interest. [Here, there are many options, but the use of international survey data to measure corruption in cross-national analyses is the first that occurs to me.] This would potentially broaden the readership and impact of the Letter. If you are concerned about space, I note that the final 2 paragraphs (especially the last) are a bit repetitive and not strictly necessary for such a short
piece. Adding a paragraph to the discussion or revising the conclusion to incorporate a discussion of the implications for other literatures, the two methodological points raised by Reviewer 1, and/or related methodological questions that require additional research would help highlight the methodological points raised by the Letter. Revising the abstract to be less about a replication per se and emphasize more clearly the contribution by being more specific than "we correctly take measurement uncertainty into account" would serve a similar purpose.

**Comment by casstai** [comment]
add method contribution in introduction [c10ea28](https://github.com/fsolt/dcpo_dem_mood/commit/c10ea28e1013e196cf57a46d665bd2f932b26dc4) and conclusion [7a88324](https://github.com/fsolt/dcpo_dem_mood/commit/7a88324764c199bcd6e3d78a3977ff0e14923f4d).
