### ISSUE TITLE
Final version of the manuscript

### ISSUE THREAD

**Issue by sammo3182** [fsolt/dcpo_dem_mood#36]
# Email

> When you revise the final manuscript, please add notes to your figures (or in the text describing the
figures, as you prefer) indicating that the full tables with specification results are available in the
Supplemental Materials.

# Guide

> You should upload in a .zip file all files needed to render the .pdf. This includes the .bib,
.bbl, and .bst files as well as any author-defined macros and style files. These should be
uploaded to Editorial Manager as "For Production - Not Compiled."

>  If your Supplementary Materials (see below) are included in your main .tex file, please
remove references \ref{} in main text to figures and tables in the appendix. We do not
send figures/tables from the appendix to our typesetters and this creates a lot of added
confusion.

>  Please include the PDF version in the event that any comparisons need to be made (this
should be submitted under "Anonymous Manuscript" in Editorial Manager).

## Format

> - Your paper must be in American English and use the Chicago Manual of Style 17th edition formatting. Additional details about references are available in the Submission Guidelines.
> - Please use section titles only, without numbers (Appendix A and B, etc. being the only exceptions).
> 	+ Instead, use the section title, or possibly the order in which it follows (e.g., "in the next section"). Please revise your manuscript before sending the text files, as this will eliminate errors and confusion at the typesetting stage.
> - Confirm footnotes are all correct.
> - Confirm math and/or proofs are correctly labeled. Please note that our journal publishes in two columns, which often breaks up equations awkwardly.
> - Tables should remain as text and not submitted as figures.
> - Take special care in preparing the Supplementary Materials document (usually a .pdf) for online publication on Cambridge's Core Website.
> 	+ Supplementary Materials will not be edited or typeset, so please make sure they are correct and appear the way you wish them to look.
> 	+ Once they are online, they cannot be changed.
> 	+ We ask you to limit the length of the Supplementary Materials to 25 (or, in exceptional cases, 30) pages.

## Figures and Tables

> - Supply figures as separate files. Tables as LATEX or Word may also be supplied separately but should follow the same following naming rules as figures.
> - Number figures and tables in the order they appear in the manuscript
> - Clearly label figures and tables logically: Fig1_, Fig2_, Fig3a_, etc. or AuthorName_Fig1_etc.
> - Figures and tables must be cited in the main text of the article or letter.
> - Captions should appear in the manuscript text and not as part of the figure file.
> - Where necessary, please supply relevant copyright permissions. You are responsible for securing the copyright permissions to reuse any artwork where you are not the copyright holder. For detailed instructions on securing permissions, please review: http://www.cambridge.org/aboutus/ rights-permissions/permissions or download this PDF: Seeking Permission for Copyrighted Material

> Image resolution: 
> - Line: 1000 dpi
> - Half-tone/color: Minimally 600 dpi

- [x] Separate figures with proper figure labels and 1000 dpi
- [x] Double check the reference
- [x] Specification table in the OSM
- [ ] A zip file that can be solely compiled under "For Production - Not Compiled."
- [x] Removing cross-citations of figures and tables from the appendix
- [x] A PDF version, upload the manuscript under "Anonymous Manuscript"

**Comment by sammo3182** [comment]
Fred @fsolt I need a full citation of Solt 2020 "Modeling Dynamic Comparative Public Opinion", probably a conference paper with link or a research gate or ssrn link? So does the one Byung-Deuk, Lindsey and you wrote ("Public Gender Egalitarianism: A Dataset of Dynamic Comparative Public Opinion Toward Egalitarian Gender Roles in the Public Sphere")

**Comment by fsolt** [comment]
(Re-)added the SocArXiv link at 8a8f52014afa068fd01ff08ba8ff7cdf5d2bda57—I much prefer SocArXiv (and OSF generally) to Researchgate and SSRN (both of which are for-profit).

**Comment by fsolt** [comment]
@sammo3182 (Re-re-)added the SocArXiv link for Solt2020 and added the new link for WooEtAl2022 at https://github.com/fsolt/dcpo_dem_mood/commit/4357fc4fbf451aa27321f62c27317ef12677d11c
