### ISSUE TITLE
Tweet

### ISSUE THREAD

**Issue by sammo3182** [fsolt/dcpo_dem_mood#39]
# Guide

> In order to promote articles on social media and increase the visibility of scholars, we encourage authors to prepare and submit to apsr@apsanet.org 1-2 suggested tweets about the article when they submit their final manuscript. Tweets should contain a maximum of 280 characters, a catchy message, and relevant additions (i.e., hashtags). See the following blogs for further suggestions on how to write an effective tweet:
> - [How to write the perfect Tweet](https://blog.stellapop.com/creative-insights/breaking-the-internet-how-to-write-the-perfect-tweet)
> - [3 formulates to get started on Twitter](https://blog.hubspot.com/marketing/tweet-formulas-to-get-you-started-on-twitter)

**Comment by fsolt** [comment]
Think democracy depends on public support? Or that public support rallies as democracy declines? @TaiYuehong, @yuehupolisci, and @fredericksolt show that when measurement uncertainty is taken into account, there is no evidence for either relationship in the short run [article link]

**Comment by fsolt** [comment]
Are there latent variables in your research? Skipping their measurement error in your analysis can lead to unsupported conclusions, @TaiYuehong, @yuehupolisci, and @fredericksolt demonstrate [article link]
