### ISSUE TITLE
analysis: add models 2-4

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_dem_mood#9]
- [x] Model 2: Pooled OLS by regime type
- [x] Model 3: GMM
- [ ] Model 4: GMM by regime type

**Comment by sammo3182** [comment]
Getting computational errors when running the GMM by regime type 

```
Error in solve.default(crossprod(WX, t(crossprod(WX, A1)))) : 
  Lapack routine dgesv: system is exactly singular: U[3,3] = 0
```

The error rose at the step of `gmm` estimation: 
https://github.com/fsolt/dcpo_dem_mood/blob/af81b264f9c4d24462bbaab19d21f33a49debd5a/paper/dcpo_demsupport.Rmd#L341-L349

It looks like that adding the uncertainties brings both more accurate estimates and more difficulty of identification.

You can replicate the error by running https://github.com/fsolt/dcpo_dem_mood/blob/af81b264f9c4d24462bbaab19d21f33a49debd5a/paper/dcpo_demsupport.Rmd#L402

@fsolt

**Comment by sammo3182** [comment]
I bet, this plot provides better evidence to show the reviewers that it's not the efficiency issue causing the null results but Claassen missed something important.

![image](https://user-images.githubusercontent.com/6463211/89712485-b6fb6400-d9c3-11ea-9c0d-6f12416d8da1.png)

On the other hand, shame on me but I can't figure out how to draw the ideal version of it with `facet`. There's always a NA column drawn automatically and unremovably. (See my desperate commit e58eb58c58f9d7c570f4de9a286758c1b34493d6)
